-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.9,
        blur = {
            passes = 4,
            size = 1,
        },
        dim_inactive = false,
        inactive_opacity = 0.85,
        rounding = 3,
    },
    general = {
        border_size = 1,
        col = {
            active_border = {
                colors = {"rgba(77767bff)", "rgba(3d3846ff)"},
                angle = 45,
            },
        },
        gaps_in = 2,
        gaps_out = 4,
    },
})

-- Keybinds
hl.unbind("SUPER + Q")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"))
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.window.close())
hl.unbind("SUPER + V")
hl.bind("SUPER + grave", hl.dsp.window.float({ action = "toggle" }))
hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.exec_cmd("helium-browser"))
hl.unbind("SUPER + Print")
hl.bind("SUPER + Print", hl.dsp.exec_cmd("hyprshot -m region"))
hl.unbind("SUPER + C")
hl.bind("SUPER + C", hl.dsp.exec_cmd("~/.local/bin/zed"))
hl.unbind("SUPER + M")
hl.bind("SUPER + M", hl.dsp.exec_cmd("flatpak run com.spotify.Client"))
